/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRecruiterRouteImport } from './routes/app/recruiter'
import { Route as AppMatchRouteImport } from './routes/app/match'
import { Route as AppDashboardRouteImport } from './routes/app/dashboard'
import { Route as AppAssistantRouteImport } from './routes/app/assistant'
import { Route as AppAnalyzerRouteImport } from './routes/app/analyzer'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRecruiterRoute = AppRecruiterRouteImport.update({
  id: '/recruiter',
  path: '/recruiter',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppMatchRoute = AppMatchRouteImport.update({
  id: '/match',
  path: '/match',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAssistantRoute = AppAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAnalyzerRoute = AppAnalyzerRouteImport.update({
  id: '/analyzer',
  path: '/analyzer',
  getParentRoute: () => AppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/app/analyzer': typeof AppAnalyzerRoute
  '/app/assistant': typeof AppAssistantRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/match': typeof AppMatchRoute
  '/app/recruiter': typeof AppRecruiterRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/app/analyzer': typeof AppAnalyzerRoute
  '/app/assistant': typeof AppAssistantRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/match': typeof AppMatchRoute
  '/app/recruiter': typeof AppRecruiterRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/app/analyzer': typeof AppAnalyzerRoute
  '/app/assistant': typeof AppAssistantRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/match': typeof AppMatchRoute
  '/app/recruiter': typeof AppRecruiterRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/app/analyzer'
    | '/app/assistant'
    | '/app/dashboard'
    | '/app/match'
    | '/app/recruiter'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/auth'
    | '/app/analyzer'
    | '/app/assistant'
    | '/app/dashboard'
    | '/app/match'
    | '/app/recruiter'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/app/analyzer'
    | '/app/assistant'
    | '/app/dashboard'
    | '/app/match'
    | '/app/recruiter'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/recruiter': {
      id: '/app/recruiter'
      path: '/recruiter'
      fullPath: '/app/recruiter'
      preLoaderRoute: typeof AppRecruiterRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/match': {
      id: '/app/match'
      path: '/match'
      fullPath: '/app/match'
      preLoaderRoute: typeof AppMatchRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/assistant': {
      id: '/app/assistant'
      path: '/assistant'
      fullPath: '/app/assistant'
      preLoaderRoute: typeof AppAssistantRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/analyzer': {
      id: '/app/analyzer'
      path: '/analyzer'
      fullPath: '/app/analyzer'
      preLoaderRoute: typeof AppAnalyzerRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppAnalyzerRoute: typeof AppAnalyzerRoute
  AppAssistantRoute: typeof AppAssistantRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppMatchRoute: typeof AppMatchRoute
  AppRecruiterRoute: typeof AppRecruiterRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppAnalyzerRoute: AppAnalyzerRoute,
  AppAssistantRoute: AppAssistantRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppMatchRoute: AppMatchRoute,
  AppRecruiterRoute: AppRecruiterRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
